#!/usr/bin/env python
# -*- coding: latin-1 -*-

"""Constants."""

COUNTRIES = {
    "(choose)": "-2",
    "Afghanistan": "156",
    "Albania": "1",
    "Algeria": "145",
    "Argentina": "2",
    "Armenia": "3",
    "Australia": "124",
    "Austria": "4",
    "Azerbaijan": "5",
    "Bahrain": "6",
    "Bangladesh": "7",
    "Belarus": "127",
    "Belgium": "8",
    "Benin Republic": "162",
    "Bhutan": "147",
    "Bolivia": "9",
    "Bosnia and Herzegovina": "10",
    "Botswana": "125",
    "Brazil": "11",
    "Brunei Darussalam": "12",
    "Bulgaria": "13",
    "Cameroon": "14",
    "Canada": "15",
    "Chile": "16",
    "China": "17",
    "Colombia": "18",
    "Costa Rica": "19",
    "Croatia": "20",
    "Cuba": "21",
    "Cyprus": "22",
    "Czech Republic": "95",
    "Denmark": "23",
    "Ecuador": "142",
    "Egypt": "24",
    "El Salvador": "159",
    "Eritrea": "25",
    "Estonia": "26",
    "Ethiopia": "27",
    "Finland": "28",
    "France": "29",
    "Georgia": "30",
    "Germany": "31",
    "Ghana": "32",
    "Greece": "33",
    "Guatemala": "160",
    "Honduras": "163",
    "Hong Kong": "34",
    "Hungary": "35",
    "India": "36",
    "Indonesia": "37",
    "Iran": "38",
    "Iraq": "135",
    "Israel": "39",
    "Italy": "40",
    "Jamaica": "41",
    "Japan": "42",
    "Jordan": "43",
    "Kazakhstan": "44",
    "Kenya": "45",
    "Korea": "46",
    "Kosovo": "118",
    "Kuwait": "47",
    "Latvia": "48",
    "Lebanon": "49",
    "Libya": "50",
    "Liechtenstein": "126",
    "Lithuania": "51",
    "Luxembourg": "120",
    "Macedonia": "52",
    "Madagascar": "138",
    "Malawi": "136",
    "Malaysia": "53",
    "Malta": "54",
    "Mauritius": "55",
    "Mexico": "56",
    "Mongolia": "57",
    "Montenegro": "119",
    "Morocco": "58",
    "Mozambique": "113",
    "Myanmar": "59",
    "Namibia": "60",
    "Nepal": "61",
    "Netherlands": "62",
    "New Zealand": "63",
    "Nigeria": "64",
    "Norway": "65",
    "Oman": "66",
    "Pakistan": "67",
    "Palestine": "141",
    "Panama": "143",
    "Paraguay": "69",
    "Peru": "70",
    "Philippines": "71",
    "Poland": "72",
    "Portugal": "73",
    "Qatar": "74",
    "Republic of Ireland": "75",
    "Republic of Yemen": "76",
    "Reunion Island": "140",
    "Romania": "77",
    "Russia": "78",
    "Rwanda": "137",
    "Saudi Arabia": "79",
    "Senegal": "157",
    "Serbia": "81",
    "Seychelles": "139",
    "Sierra Leone": "155",
    "Singapore": "82",
    "Slovakia": "83",
    "Slovenia": "84",
    "South Africa": "85",
    "South Sudan": "154",
    "Spain": "86",
    "Sri Lanka": "87",
    "St. Kitts and Nevis": "164",
    "Sudan": "88",
    "Suriname": "158",
    "Sweden": "89",
    "Switzerland": "90",
    "Syria": "91",
    "Taiwan": "92",
    "Tajikistan": "148",
    "Tanzania": "93",
    "Thailand": "94",
    "The Republic of Moldova ": "122",
    "Trinidad and Tobago": "144",
    "Tunisia": "96",
    "Turkey": "97",
    "Turkmenistan": "149",
    "Uganda": "98",
    "Ukraine": "99",
    "United Arab Emirates": "100",
    "United Kingdom": "101",
    "Uruguay": "102",
    "Uzbekistan": "103",
    "Venezuela": "104",
    "Vietnam": "105",
    "Zambia": "106",
    "Zimbabwe": "107",
}

CITIES = {
    "Any": "0",
    "Belo Horizonte": "Belo Horizonte",
    "Brasília": "Brasília",
    "Curitiba": "Curitiba",
    "Fortaleza": "Fortaleza",
    "Porto Alegre": "Porto Alegre",
    "Recife": "Recife",
    "Rio de Janeiro": "Rio de Janeiro",
    "Sao Paulo": "Sao Paulo"
}

MODULES = {
    "(choose)": "-2",
    "Academic": "1",
    "General Training": "2"
}
